version: '3.3'
services:
  gourmet-game:
    build: ./
    container_name: gourmet-game
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - docker
networks:
  docker:
    driver: bridge